function initProducts() {   
    console.log(localStorage.getItem('products'));

    if (localStorage.getItem("products") == null) {
        console.log(123);
        let products = [
            {
                id:1,
                title:'Taylor AD17E',
                img:'./img/product/dan1.png',
                category:'Taylor',
                categoryMain:'guitar acoustic',
                details:['Một cây đàn chuyên nghiệp','Tự hào được sản xuất tại Mỹ','Gỗ được lựa chọn kỹ lưỡng cho âm thanh tốt','Mặt trên bằng vân sam cứng - một tiêu chuẩn guitar acoustic lâu đời','Back & Side là gỗ Solid ovangkol – đặc tính âm tương tự như gỗ Rosewood'],
                price:44100000,
            },
            {
                id:2,
                title:'Taylor 114CE-S',
                img:'./img/product/dan2.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Mặt Top Solid Spruce, mặt hông và sau là gỗ Sapele','Body dáng Grand Auditorium','Cần đàn gỗ Hard Rock Maple','Mặt phím Western African Crelicam Ebony',' Pickup Taylor ES-2'],
                price:22320000,
            },
            {
                id:3,
                title:'Taylor 110CE-S',
                img:'./img/product/dan3.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Mặt Top Solid Spruce, mặt hông và sau là gỗ Sapele','Body dáng Dreadnought','Cần đàn gỗ Hard Rock Maple','Mặt phím Western African Crelicam Ebony','Pickup Taylor ES-2'],
                price:22320000,
              
                
            },
            {
                id:4,
                title:'Taylor 310CE',
                img:'./img/product/dan4.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Dáng Dreadnought - các flatpicker âm thanh mạnh mẽ và các strummer love',
    
                   ' Khung Forward Shifted với Relief Rout',
                    
                     'Loại gỗ: Sapele: âm gỗ tuyệt vời cho mọi mục đích chơi nhạc',
                    
                     'Đường cắt: phong cách Venice: đường cắt phổ biến, cong dịu dàng',
                    
                     'Điện tử: hệ thống Expression: khuếch trương âm acoustic trầm'],
                price:60530000,
            },
            {
                id:5,
                title:'Taylor Academy A12E',
                img:'./img/product/dan5.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Thân đàn nhỏ gọn dễ chịu thích hợp với lối chơi fingerpicking',
    
                 'Mặt trước gỗ Sitka nguyên miếng cho âm thanh linh hoạt và độ vang lớn',
                
                 'Thân đàn bằng các lớp gỗ sapele mang đến một khung đàn chắc chắn'
                ,
                 'Bàn phím bằng gỗ mun được trang trí với các nốt họa tiết acrylic Ý 4mm',
                
                 'Hệ thống điện tử ES-B tích hợp tuner cho tông âm khuếch đại cực chi tiết',
                
                'Thiết kế độc đáo kết hợp với mức giá phải chăng'],
                price:20170000,
                
            },
            {
                id:6,
                title:'Taylor Academy A10E',
                img:'./img/product/dan6.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:[' Dáng dreadnought, thích hợp với lối chơi strumming hay flatpicking',
    
                'Mặt trước bằng gỗ Sitka nguyên miếng cho âm thanh rõ ràng,cộng hưởng',
                
               'Mặt sau và hai bên hông gỗ sapele mang đến một khung đàn chắc chắn',
                
                'Bàn phím bằng gỗ mun được trang trí với các nốt họa tiết acrylic Ý 4mm',
                
                'Sản phẩm Đi kèm bao đàn'],
                price:20170000,
            },
            {
                id:7,
                title:'Taylor 114E',
                img:'./img/product/dan7.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Dáng Grand Auditorium – hoàn hảo cho mọi mục đích chơi acoustic',
    
                 'Mặt trước đàn làm bằng gỗ Sitka Spruce cho âm thanh cộng hưởng',
                
                 'Thân đàn làm bằng gỗ Walnut mang tới chất âm cân bằng',
                
                 'Thiết bị điện tử Expression System® 2 độc quyền của Taylor',
                
                 'Kết cấu UV bảo vệ thân thiện với môi trường',
                
                 'Tay vịn giúp chơi đàn thoải mái hơn'],
                price:21100000,
            },
            {
                id:8,
                title:'Taylor Academy A10',
                img:'./img/product/dan8.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Dáng dreadnought, thích hợp với lối chơi strumming hay flatpicking',
    
                 'Mặt trước bằng gỗ Sitka nguyên miếng cho âm thanh rõ ràng,cộng hưởng',
                
                 'Mặt sau và hai bên hông gỗ sapele mang đến một khung đàn chắc chắn',
                
                 'Bàn phím bằng gỗ mun được trang trí với các nốt họa tiết acrylic Ý 4mm',
                
                 'Sản phẩm Đi kèm bao đàn'],
                price:16780000,
            },
            {
                id:9,
                title:'Taylor 712ce',
                img:'./img/product/dan9.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:[' Thiết kế nhỏ gọn và linh hoạt với Body kiểu Grand Concert',
    
                 'Mặt trước bằng gỗ Solid Lutz spruce',
                
                 'Mặt sau và 2 bên hông bằng gỗ Solid rosewood',
                
                 'Venetian cutaway, stage-ready ES2 pickup và preamp của Taylor'],
                price:'Liên hệ',
            },
            {
                id:10,
                title:'Taylor 214CE',
                img:'./img/product/dan10.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:[],
                price:29100000,
            },
            {
                id:11,
                title:'Taylor 418ce',
                img:'./img/product/dan11.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Thanh giằng Performance with Relief Rout',
    
                 'Hệ thống điện tử Expression System 2',
                
                 'Tusq Nut và Micarta Saddle'],
                price:69720000,
            },
            {
                id:12,
                title:'Taylor PS14ce, Macassar',
                img:'./img/product/dan12.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:[],
                price:272760000,
            },
            {
                id:13,
                title:'Taylor K24ce',
                img:'./img/product/dan13.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Dáng đàn acoustic đặc trưng của Taylor',
    
                 'Cutaway Venetian được biết đến với đường tròn mềm mại',
                
                 'Toàn bộ thân đàn bằng Gỗ Koa Hawaii cho vẻ đẹp và âm thanh chất lượng cao',
                
                 'Expression System® 2 cho khả năng nắm bắt được nhiều độ động hơn'],
                price:146000000,
            },
            {
                id:14,
                title:'Taylor 412CE',
                img:'./img/product/dan14.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Dáng Grand Concert -  thân nhỏ hơn phù hợp cho fingerstyle',
    
                 'Khung: Forward Shifted với Relief Rou',
                
                 'Mặt trước đàn làm bằng gỗ Sitka Spruce rắn',
                
                 'Mặt sau và hai bên hông đàn làm bằng gỗ Ovangkol',
                
                 'Đường cắt Venetian cutaway được biết đến với đường cong mềm mại'],
                price:75500000,
            },
            {
                id:15,
                title:'Taylor 414CE',
                img:'./img/product/dan15.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Hình dạng : Grand Auditorium',
    
                 'Khung : Forward Shifted với Relief Rout',
                
                 'Loại gỗ: Ovangkol, cùng họ với gỗ rosewood',
                
                 'Đường cắt: phong cách Venice cong dịu dàng',
                
                 'Hệ thống Expression khuếch trương âm trầm acoustic'],
                price:75390000,
            },
    
            {
                id:16,
                title:'Taylor 114CE',
                img:'./img/product/dan16.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Dáng Grand Auditorium hoàn hảo cho mọi mục đích chơi acoustic',
    
                 'Mặt trước đàn làm bằng gỗ Sitka Spruce cho âm thanh cộng hưởng',
                
               'Thân đàn làm bằng gỗ Walnut mang tới chất âm cân bằng',
                
                 'Thiết bị điện tử Expression System® 2 độc quyền của Taylor',
                
                 'Kết cấu UV bảo vệ thân thiện với môi trường'],
                price:26070000,
            },
            {
                id:17,
                title:'TAYLOR 512CE',
                img:'./img/product/dan17.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Dáng Grand concert vừa vặn, dễ sử dụng',
    
                 'Khung: Forward Shifted với Relief Rout',
                
                  'Gỗ Mahogany nhiệt đới: tự hào bởi độ cân bằng và độ thẩm mỹ',
                
                 'Đường cắt phong cách Venice: đường cắt phổ biến đường cong dịu dàng'],
                price:'Liên hệ',
            },
            {
                id:18,
                title:'Taylor 712ce',
                img:'./img/product/dan18.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Thiết kế nhỏ gọn và linh hoạt với Body kiểu Grand Concert',
    
                 'Mặt trước bằng gỗ Solid Lutz spruce',
                
                 'Mặt sau và 2 bên hông bằng gỗ Solid rosewood',
                
                 'Venetian cutaway, stage-ready ES2 pickup và preamp của Taylor'],
                price:'Liên hệ',
            },
            {
                id:19,
                title:'Taylor 812ce',
                img:'./img/product/dan19.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Kiểu dáng Grand concert cutaway',
    
                 'Thanh giằng hiệu suất cao với relief rout',
                
                 'Mặt trước gỗ Solid sitka spruce',
                
                 'Mặt sau và bên hông: Massive rosewood'],
                price:'Liên hệ',
            },
            {
                id:20,
                title:'Taylor 210CE',
                img:'./img/product/dan20.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:[' Dáng đàn dreadnought cutaway cho âm thanh ở mid và treble đều tràn đầy năng lượng',
    
                 'Thân đàn bằng gỗ Layered Rosewoodmang lại giai điệu tuyệt vời',
                
                 'Tích hợp hệ thống Expression Pick-up System độc quyền của Taylor',
                
                 'Kết cấu UV thân thiện với môi trường'],
                price:'Liên hệ',
            },
            {
                id:21,
                title:'Taylor 312CE',
                img:'./img/product/dan21.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:[],
                price:'Liên hệ',
            },
            {
                id:22,
                title:'Taylor 314CE',
                img:'./img/product/dan22.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:[],
                price:57500000,
            },
            {
                id:23,
                title:'Taylor 914ce',
                img:'./img/product/dan23.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:[' Kiểu dáng Grand Auditorium',
    
                 'Mặt trước bằng gỗ Sitka Spruce',
                
                 'Mặt sau và 2 bên hông gỗ Solid Indian rosewood',
                
                 'Thanh giằng V-Class™ bracing'],
                price:154350000,
            },
            {
                id:24,
                title:'Taylor 714ce',
                img:'./img/product/dan24.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Phong cách thể thao và linh hoạt với Body kiểu Grand Auditorium','Mặt trước bằng gỗ Solid Lutz spruce','Mặt sau và 2 bên hông bằng gỗ Solid rosewood','Venetian cutaway, stage-ready ES2 pickup và preamp của Taylor'],
                price:89250000,
            },
            {
                id:25,
                title:'Taylor 814ce',
                img:'./img/product/dan25.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Kiểu dáng: Grand Auditorium',
    
                 'Mặt trước Solid Sitka spruce',
                
                 'Mặt sau và bên hông: Solid rosewood ',
                
                 'Mặt phím và ngựa đàn: Ebony'],
                price:112190000,
            },
            {
                id:26,
                title:'Big Baby Taylor',
                img:'./img/product/dan26.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Kích thước 15/16 dáng Dreadnought',
    
                 'Gỗ Sapele ép ở mặt sau và hai bên hông',
                
                 'Gỗ vân sam Sitka ở mặt trước',
                
                 'Kèm một túi gig để dễ dàng di chuyển và giúp bảo vệ đàn'],
                price:13810000,
            },
            {
                id:27,
                title:'Taylor 714ce-N',
                img:'./img/product/dan27.jpg',
                category:'Taylor',
                categoryMain:'Guitar Acoustic',
                details:['Kiểu dáng Grand Auditorium với mặt cắt Venetian mềm mại',
    
                 'Chất liệu :gỗ Lutz Spruce và  Indian Rosewood',
                
                 'Tích hợp hệ thống ES-N pickup/preamp. '],
                price:'Liên hệ',
            },
    
            {
                id:28,
                title:'Fender CD-60S',
                img:'./img/product/dan28.jpg',
                category:'Fender-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['CD-60s là một trong những mô hình phổ biến nhất của Fender và lý tưởng cho những người chơi đang tìm kiếm một cây đàn dáng dreadnought chất lượng cao giá cả phải chăng với giai điệu cùng khả năng chơi tuyệt vời '],
                price:5850000,
            },
            
            {
                id:30,
                title:'Fender FSR V3 CD60 CHY WN',
                img:'./img/product/dan30.jpg',
                category:'Fender-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['CD-60 là một trong những mô hình phổ biến nhất của Fender và lý tưởng cho những người chơi đang tìm kiếm một cây đàn dáng dreadnought chất lượng cao giá cả phải chăng với giai điệu cùng khả năng chơi tuyệt vời  '],
                price:'Liên hệ',
            },
            {
                id:31,
                title:'FENDER FSR CD-60S FLM EXT, SB WN',
                img:'./img/product/dan31.jpg',
                category:'Fender-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['CD-60S là một trong những mẫu acoustic phổ biến nhất của Fender, mang đến giai điệu và khả năng chơi tuyệt vời với giá cả phải chăng. Mẫu FSR (Fender Special Run)  này có mặt Top bằng Spruce chắc chắn, được kết hợp với mặt sau và mặt bên của Flame Maple. Maple mang lại không khí sang trọng cho CD-60S. '],
                price:'Liên hệ',
            },
            {
                id:32,
                title:'Fender CC-60SCE',
                img:'./img/product/dan32.jpg',
                category:'Fender-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Dáng Concert nhỏ gọn, rất dễ chơi',
    
                 'Mặt top bằng gỗ spruce nguyên khối',
                
                 'Mặt sau và bên hông được làm từ gỗ mahogany',
                
                 'Các phím đàn trọn trịa trên mặt phím Rosewood'],
                price: 9290000,
            },
            {
                id:33,
                title:'Fender FSR V3 CD60 MAH WN',
                img:'./img/product/dan33.jpg',
                category:'Fender-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['CD-60 là một trong những mô hình phổ biến nhất của Fender và lý tưởng cho những người chơi đang tìm kiếm một cây đàn dáng dreadnought chất lượng cao giá cả phải chăng với giai điệu cùng khả năng chơi tuyệt vời. '],
                price:5300000,
            },
            {
                id:34,
                title:'Fender CD-140SCE',
                img:'./img/product/dan34.jpg',
                category:'Fender-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Thiết kế hiện đại. Thùng đàn lớn cho tiếng đàn to, ấm và đầy',
    
                     'Nhiều tính năng hiện đại, đánh bật mọi cảm xúc khi chơi'],
                price:10890000,
            },
            {
                id:35,
                title:'Fender CC-60S',
                img:'./img/product/dan35.jpg',
                category:'Fender-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Dáng Concert nhỏ gọn, rất dễ chơi',
    
                'Mặt top bằng gỗ spruce nguyên khối',
                
                'Mặt sau và bên hông được làm từ gỗ mahogany',
                
                'Các phím đàn trọn trịa trên mặt phím Rosewood'],
                price:5850000,
            },
            {
                id:36,
                title:'Fender CD-60SCE',
                img:'./img/product/dan36.jpg',
                category:'Fender-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Dáng Dreadnought cutaway cho âm thanh dày, ngân lâu',
    
                 'Mặt top bằng gỗ spruce nguyên khối',
                
                 'Mặt sau và bên hông được làm từ gỗ mahogany',
                
                 'Các phím đàn trọn trịa trên mặt phím Rosewood',
                
                 'Sử dụng pick-up của Fishman với EQ 3-band'],
                price:9290000,
            },
            {
                id:37,
                title:'Fender CC-60S Sunburst',
                img:'./img/product/dan37.jpg',
                category:'Fender-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Dáng Concert nhỏ gọn, rất dễ chơi',
    
                 'Mặt top bằng gỗ spruce nguyên khối',
                
                 'Mặt sau và bên hông được làm từ gỗ mahogany',
                
                 'Các phím đàn trọn trịa trên mặt phím Rosewood'],
                price:5850000
            },
            {
                id:38,
                title:'Fender CD-140SCE-12 NAT WC ',
                img:'./img/product/dan38.jpg',
                category:'Fender-acoustic',
                categoryMain:'Guitar Acoustic',
                details:[' Thiết kế thùng đàn lớn cho tiếng đàn to, ấm và đầy hơn',
    
                 'Âm thanh tuyệt vời, tạo hứng thú cho người chơi',
                
                 'Preamp của Fishman® mang lại hiệu suất khuếch đại vô song',
                
                 'Mua hàng trả góp lãi suất 0%.Bảo hành chính hãng.'],
                price:'Liên hệ',
            },
            {
                id:39,
                title:'Takamine GD10CE',
                img:'./img/product/dan39.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Dáng đàn dreadnought cho âm thanh dày, mạnh mẽ',
    
                 'Mặt trước gỗ Spruce kết hợp mặt sau và hông mahogany',
                
                 'Cần đàn mỏng gỗ mahogany và bán kính 12',
                
                 'Mặt phím gỗ và ngựa đàn Pin-less gỗ ovangkol',
                
                 'Hệ thống điện tử Takamine TP-4T với Tuner tích hợp'],
                price:8730000,
            },
            {
                id:40,
                title:'Takamine GD93CE-NAT',
                img:'./img/product/dan40.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Dáng dreadnought khác biệt với vẻ ngoài tinh tế và hiện đại',
    
                 'Cấu trúc gỗ nguyên miếng ở mặt trước và mặt sau ba mảnh khác lạ',
                
                 'Âm thanh phong phú, đanh và vang mạnh mẽ',
                
                 'Cần đàn bằng gỗ Gụ giúp cân bằng âm thanh',
                
                 'Hệ thống Pre-amp được tích hợp sẵn'],
                price:14840000,
            },
            {
                id:41,
                title:'Takamine GN10-NS',
                img:'./img/product/dan41.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:[],
                price:5820000,
            },
            {
                id:42,
                title:'Takamine GD15CE',
                img:'./img/product/dan42.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:[],
                price: 9530000,
            },
            {
                id:43,
                title:'Takamine GD71CE',
                img:'./img/product/dan43.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Mặt trước bằng gỗ vân sam nguyên miếng kết hợp Mặt sau và 2 bên hông gỗ hồng mộc mang đến những âm thanh dày và lớn',
    
                 'Cần đàn bằng gỗ Gụ mảnh khảnh với độ cong cần có bán kính là 12 inch gắn chặt với phím đàn bằng gỗ hồng mang lại những cảm giác vô cùng tuyệt vời khi chơi và dễ sử dụng để chơi nhiều phong cách khác nhau',
                
                 'Hệ thống preamp onboard của Takamine có thêm 3 dải EQ tăng thêm khả năng kiểm soát âm thanh'],
                price:'Liên hệ',
            },
            {
                id:44,
                title:'Takamine GD51CE8',
                img:'./img/product/dan44.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Mặt trước bằng gỗ Spruce nguyên miếng',
    
                 'Mặt sau và hông bằng gỗ Rosewood',
                
                 'Cần đàn Mahogay với mặt phím Bound Rosewood',
                
                 'Cần đàn mảnh khảnh với độ cong cần có bán kính là 12',
                
                 'Hệ thống preamp onboard của Takamine có thêm 3 dải EQ'],
                price:10000000,
            },
            {
                id:45,
                title:'Takamine GD51',
                img:'./img/product/dan45.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:[' Phong cách dreadnought với những đặc điểm cao cấp trong thiết kế',
    
                 'Mặt trên gỗ Spruce nguyên miếng cho âm thanh vang, cộng hưởng nhất',
                
                 'Cần đàn thanh mảnh bằng gỗ Gụ với độ cong cần đàn bán kính 12',
                
                 'Phím đàn bằng gỗ hồng. Lưng ngựa đàn chẻ bằng gỗ hồng'],
                price:8260000,
            },
            {
                id:46,
                title:'Takamine GN93CE',
                img:'./img/product/dan46.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Thiết kế theo phong cách NEX body hiện đại',
    
                 'Mặt trên làm bằng gỗ spruce',
                
                 'Mặt sau ghép tinh tế: 2 miếng rosewood và 1 miếng maple ở giữa',
                
                 'Cần đàn bằng gỗ gụ mỏng. Cần đàn và đầu đàn đều được viền tinh xảo'],
                price:14840000,
            },
            {
                id:47,
                title:'Takamine GN71CE',
                img:'./img/product/dan47.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Được thiết kế với dáng NEX hiện đại',
    
                 'Venetian cutaway với các đường cong mềm mại',
                
                 'Mặt trên bằng gỗ spruce nguyên miếng',
                
                 'Mặt sau và hông đàn bằng gỗ rosewood nguyên miếng',
                
                 'Cần đàn gỗ gụ với mặt phím gỗ Bound Rosewood'],
                price:'Liên hệ',
            },
            {
                id:48,
                title:'Takamine GN51CE',
                img:'./img/product/dan48.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Được thiết kế với dáng NEX hiện đại',
    
                 'Venetian cutaway với các đường cong mềm mại',
                
                 'Mặt trên bằng gỗ spruce nguyên miếng',
                
                 'Mặt sau và hông đàn bằng gỗ rosewood nguyên miếng',
                
                 'Cần đàn gỗ gụ với mặt phím gỗ Bound Rosewood'],
                price:11300000,
            },
            {
                id:49,
                title:'Takamine P4DC',
                img:'./img/product/dan49.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Gỗ vân sam nguyên miếng ở mặt trước',
    
                 'Gỗ Sapele nguyên miếng cho mặt sau, Sapele cho hai bên hông',
                
                 'Cần đàn gỗ Mahogany với mặt phím gỗ rosewood',
                
                 'Hệ thống CTP-3 Cool Tube™ preamp độc quyền của Takamine kết nối với hệ thống Palathetic™ độc đáo bên dưới pickup saddle'],
                price:34160000,
            },
            {
                id:50,
                title:'Takamine P5DC',
                img:'./img/product/dan50.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:['Gỗ vân sam nguyên miếng ở mặt trước',
    
                 'Gỗ Sapele nguyên miếng cho mặt sau, Sapele cho hai bên hông',
                
                 'Cần đàn gỗ Mahogany với mặt phím gỗ rosewood',
                
                 'Hệ thống CTP-3 Cool Tube™ preamp độc quyền của Takamine kết nối với hệ thống Palathetic™ độc đáo bên dưới pickup saddle'],
                price:'Liên hệ',
            },
            {
                id:51,
                title:'Takamine P5NC',
                img:'./img/product/dan51.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:[],
                price:40650000,
            },
            {
                id:52,
                title:'Takamine P3MC',
                img:'./img/product/dan52.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:[],
                price:29740000,
            },
            {
                id:53,
                title:'Takamine P1DC',
                img:'./img/product/dan53.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:[],
                price:31980000,
            },
            {
                id:54,
                title:'Takamine P1NC',
                img:'./img/product/dan54.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:[],
                price:27580000,
            },
            {
                id:55,
                title:'Takamine P2DC',
                img:'./img/product/dan55.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:[],
                price:28810000,
            },
            {
                id:56,
                title:'Takamine P3DC',
                img:'./img/product/dan56.jpg',
                category:'Takamine-acoustic',
                categoryMain:'Guitar Acoustic',
                details:[],
                price:'Liên hệ',
            },  
           
            {
                id:58,
                title:'Suzuki SDG-6NL',
                img:'./img/product/dan58.jpg',
                category:'Suzuki',
                categoryMain:'Guitar Acoustic',
                details:['Nổi bật với kiểu dáng hiện đại, bắt mắt',
    
                'Thùng đàn được thiết kế dày tạo âm thanh trong và vang.',
                
                 'Giá phải chăng, rất thích hợp cho người mới chơi, học sinh, sinh viên, người chơi có thu nhập thấp.'],
                price:2916000,
            },
            {
                id:59,
                title:'Suzuki SDG-15NL',
                img:'./img/product/dan59.jpg',
                category:'Suzuki',
                categoryMain:'Guitar Acoustic',
                details:['Nổi bật với thiết kế trang nhã, âm thanh tuyệt vời',
    
                     'Được làm từ các vật liệu cao cấp, cho độ bền cao',
                    
                     'Mức giá phải chăng, phù hợp với người mới chơi, học sinh, sinh viên…'],
                price:3153000,
            },
            {
                id:60,
                title:'Suzuki SDG-45CE NL',
                img:'./img/product/dan60.jpg',
                category:'Suzuki',
                categoryMain:'Guitar Acoustic',
                details:[],
                price:4470000,
            },
            {
                id:61,
                title:'ORTEGA R121 guitar',
                img:'./img/product/61.jpg',
                category:'Ortega',
                categoryMain:'Guitar Classic',
                details:['ORTEGA R121 guitar Otega là một thương hiệu được biết đến với việc chuyên sản xuất những cây đàn có âm thanh theo phong cách Tây Ban Nha cổ điển. R121 - một cây guitar Ca'],
                price:5240000,
            },
            {
                id:62,
                title:'ORTEGA R131SN guitar',
                img:'./img/product/dan62.jpg',
                category:'Ortega',
                categoryMain:'Guitar Classic',
                details:['Thông tin sản phẩm:  Gỗ tuyết tùng rắn Mặt sau và mặt bên: Gỗ gụ'],
                price:6990000,
            },
            {
                id:63,
                title:'ORTEGA RCE159MN guitar/elec',
                img:'./img/product/dan63.jpg',
                category:'Ortega',
                categoryMain:'Guitar Classic',
                details:['ORTEGA RCE159MN guitar/elec Được trang bị bộ điều chỉnh điện tử Ortega MagusPro  Đầu đàn trung bình (50 mm / 1,97 ") Tính năng bàn phím'],
                price:11660000,
            },
            {
                id:64,
                title:'ORTEGA R122SN guitar',
                img:'./img/product/dan64.jpg',
                category:'Ortega',
                categoryMain:'Guitar Classic',
                details:['ORTEGA R122SN guitar R122SN là một phần của Family Series của Ortega, tập trung vào những người chơi ở cấp độ mới và sự thoải mái của họ. '],
                price:5240000,
            },
            {
                id:65,
                title:'ORTEGA R131 guitar',
                img:'./img/product/dan65.jpg',
                category:'Ortega',
                categoryMain:'Guitar Classic',
                details:[],
                price:6990000,
            },
            {
                id:66,
                title:'ORTEGA R122 guitar ',
                img:'./img/product/dan66.jpg',
                category:'Ortega',
                categoryMain:'Guitar Classic',
                details:['ORTEGA R131 guitar Thông tin cơ bản của sản phẩm Gỗ tuyết tùng rắn Mặt sau và mặt bên: Gỗ gụ'],
                price:4500000,
            },
            {
                id:67,
                title:'ORTEGA R139MN guitar',
                img:'./img/product/dan67.jpg',
                category:'Ortega',
                categoryMain:'Guitar Classic',
                details:[' ORTEGA R139MN guitar Ortega Ortega R139MN cung cấp các tông màu ấm áp nổi bật nhờ mặt trên bằng gỗ tuyết tùng cứng và mặt sau và mặt sau bằng sapele'],
                price:7990000,
            },
            {
                id:68,
                title:'ORTEGA RCE158SN-HSB guitar/elec',
                img:'./img/product/dan68.jpg',
                category:'Ortega',
                categoryMain:'Guitar Classic',
                details:['ORTEGA RCE158SN-HSB guitar/elec Được trang bị bộ điều chỉnh điện tử Ortega MagusPro của chúng tôi Đầu đàn mỏng (48 mm / 1,89 ") '],
                price:9960000,
            },
            {
                id:69,
                title:'ORTEGA R121SN guitar',
                img:'./img/product/dan69.jpg',
                category:'Ortega',
                categoryMain:'Guitar Classic',
                details:[],
                price:5240000,
            },
            {
                id:70,
                title:'ORTEGA R121-3/4 guitar',
                img:'./img/product/dan70.jpg',
                category:'Ortega',
                categoryMain:'Guitar Classic',
                details:['Đây là một sản phẩm dành cho những người chơi nhỏ tuổi của thương hiệu Ortega.', 
                         'Cây đàn có màu tự nhiên, mặt trước được làm từ gỗ Spruce, mặt sau và hông làm từ gỗ gụ. Âm thanh đặc trưng, hoàn hảo của guitar Classical vang ấm, phù hợp mọi lối chơi cho người mới bắt đầu. '],
                price:3990000,
            },
            {
                id:71,
                title:'Takamine TC132SC',
                img:'./img/product/dan71.jpg',
                category:'Takamine-classic',
                categoryMain:'Guitar Classic',
                details:['Cây đàn guitar cổ điển sử dụng dây nilon này tuân thủ thiết kế của nhạc cụ truyền thống và bám sát bản vẽ gốc của Antonio Torres. Đây là sự lựa chọn đầu tiên của nghệ sĩ chơi nhạc latin và jazz truyền thống, khi cần âm điệu của loại dây nilon thuần khiết tại mức âm lượng khuếch đại. Mặt trên làm bằng gỗ tuyết tùng nguyên miếng cho âm dày và ấm với nhiều dải động. Mặt lưng bằng gỗ hồng mộc tạo tiếng vang tốt và giúp chất lượng âm thanh đạt đến độ tuyệt hảo. Cần đàn bằng gỗ Gụ với cặp truss rod để chiếc guitar chơi hoàn hảo trong mọi môi trường.'],
                price:46190000,
            },
            {
                id:72,
                title:'Takamine TC135SC',
                img:'./img/product/dan72.jpg',
                category:'Takamine-classic',
                categoryMain:'Guitar Classic',
                details:['Đàn guitar Takamine TC135SC với kiểu dáng Classic: là kiểu dáng đàn đầu tiên của cây đàn guitar trải qua hàng trăm năm không có gì thay đổi và vẫn được ưa chuộng. Dài 49cm, thân trên 29cm, thân dưới 37cm, dày 10cm.','Đàn Guitar Nhật Bản Takamine cung cấp nhiều lựa chọn về kiểu dáng, màu sắc và loại gỗ so với nhiều dòng khác. Xem giá đàn guitar Nhật Bản trên Việt Thương. Takamne được thiết kế và lắp ráp dưới sự giám sát của những thợ làm đàn hàng đầu.'],
                price:56840000,
            },
            {
                id:73,
                title:'Takamine GC3',
                img:'./img/product/dan73.jpg',
                category:'Takamine-classic',
                categoryMain:'Guitar Classic',
                details:[' là một cây guitar cổ điển được xây dựng vững chắc với mặt top, màu bóng hoàn thiện, âm thanh dây nylon tuyệt vời đúng với sự mong đợi từ người chơi guitar cổ điển như Takamine'],
                price:6600000,
            },
            {
                id:74,
                title:'Takamine C132S',
                img:'./img/product/dan74.jpg',
                category:'Takamine-classic',
                categoryMain:'Guitar Classic',
                details:['Mẫu guitar C132S được chế tác thủ công trong các cơ sở chuyên nghiệp của Takamine – nơi đã cho ra đời rất nhiều loại nhạc cụ chất lượng cao suốt hơn năm thập kỷ qua. ','Dây đàn nylon của guitar cổ điển tôn trọng nguyên mẫu của nhạc cụ truyền thống và bám sát bản vẽ gốc của Antonio Torres. Mặt trước bằng gỗ tuyết tùng nguyên miếng được hỗ trợ bởi thang giằng truyền thống, mang đến âm thanh ấm và nhiều dải âm sinh động. Mặt lưng bằng gỗ hồng mộc và hai bên hông ra những tiếng vang rất tuyệt vời. Cần đàn bằng gỗ Gụ với cặp truss rod giúp chiếc guitar có thể chơi hoàn hảo trong bất kỳ môi trường nào. Độ phủ bóng tự nhiên cung cấp độ bền và tăng thêm vẻ đẹp cho cây đàn'],
                price:24390000,
            },
            {
                id:75,
                title:'Takamine P3FCN',
                img:'./img/product/dan75.jpg',
                category:'Takamine-classic',
                categoryMain:'Guitar Classic',
                details:['Chiếc guitar dây ni lông Acoustic-electric P3FCN FXC thuộc Pro Series của Takamine sẽ khiến bạn rất thích thú với tiếng đàn ngọt ngào, vẻ ngoài tuyệt đẹp và lối chơi đa dạng của nó. Cầm đàn lên, để bàn tay của bạn chạm vào cần đàn dễ chịu bằng gỗ Gụ và thỏa sức giải trí với tiếng vang dày ấm đến từ chất liệu gỗ tuyết tùng nguyên miếng ở mặt trước. Hãy chơi nốt đơn và đưa các ngón tay lướt nhẹ nhàng trên phím đàn bằng gỗ hồng được gắn chặt vào cần đàn cùng sự tinh tế của mặt cắt Venetian của chiếc P3FCN này. Cắm thêm vào một bộ ampli để khuếch đại âm thanh của chiếc đàn, bạn sẽ có những trải nghiệm rõ ràng hơn về tiếng dây ni lông đầy thu hút. Như cách mà người ta nói về P3FCN – chơi đàn chính là yêu thương.'],
                price:29740000,
            },
            {
                id:76,
                title:'Takamine GC3CE',
                img:'./img/product/dan76.jpg',
                category:'Takamine-classic',
                categoryMain:'Guitar Classic',
                details:['Đàn guitar Takamine GC3CE-NAT là một cây guitar cổ điển được xây dựng vững chắc với mặt top, màu bóng hoàn thiện, âm thanh dây nylon tuyệt vời đúng với sự mong đợi từ người chơi guitar cổ điển như Takamine.',
                        ' Hoàn hảo cho bất kỳ người chơi tìm kiếm một cây đàn guitar cổ điển, với GC3 kết hợp gỗ vân sam rắn và gỗ gụ sau, cộng hưởng tạo nên âm thanh phong phú.'],
                price:9960000,
            },
            {
                id:77,
                title:'Takamine GC5NAT',
                img:'./img/product/dan77.jpg',
                category:'Takamine-classic',
                categoryMain:'Guitar Classic',
                details:['Đây là một ý tưởng rất tuyệt cho những người chơi đang tìm kiếm một chiếc guitar cổ điển có âm thanh tinh tế và tính cân bằng tốt. GC5 là sự kết hợp của sườn rẽ quạt, mặt trước là gỗ vân sam nguyên miếng với gỗ hồng mộc ở mặt sau và hai bên hông cùng với tone dây đàn nylon đặc trưng của guitar Takamine cổ điển. Cần đàn bằng gỗ Gụ rất dễ chịu kết hợp với phím đàn bằng gỗ hồng mộc mang lại những cảm giác vô cùng tuyệt vời khi chơi và dễ sử dụng để chơi nhiều phong cách khác nhau. Ngoài ra, thiết kế cần đàn kiểu dovetail với sự gắn kết giữa gỗ với gỗ tạo nên một cấu trúc ổn định và âm vang tuyệt vời.',
    
                'Một số đặc điểm tuyệt vời khác bao gồm: nốt hợp âm khảm rất đẹp, lược đàn và ngựa đàn được làm bằng xương, headcap bằng gỗ hồng mộc, bộ khóa đúc được mạ vàng với các chốt vặn màu trắng và cả thân đàn được phủ bóng sang trọng.'],
                price:6350000,
            },
            {
                id:78,
                title:'Takamine GC1CE',
                img:'./img/product/dan78.jpg',
                category:'Takamine-classic',
                categoryMain:'Guitar Classic',
                details:['Đàn Guitar Takamine GC1CE là một chiếc guitar acoustic-electric cổ điển khá đẹp mắt với dây nilon đặc trưng mang lại những âm thanh dày ấm và có kiểu dáng thiết kế với mặt cắt kiểu Venetian cùng hệ thống điện tử của Takamine.Đây là sự lựa chọn tuyệt vời cho những người chơi đang tìm kiếm một chiếc guitar cổ điển vừa có chất lượng tốt nhưng giá cả phải chăng'],
                price:6700000,
            },
            {
                id:79,
                title:'Takamine GC5CE',
                img:'./img/product/dan79.jpg',
                category:'Takamine-classic',
                categoryMain:'Guitar Classic',
                details:['Đàn guitar Takamine GC5CE là một guitar cao cấp với thiết kế gỗ nguyên miếng và những đặc điểm hoàn hảo: mặt cắt kiểu Venetian cùng hệ thống điện tử Electronics của Takamine. GD5CE là một cây guitar acoustic-electric được thiết kế có khả năng giúp bạn tỏa sáng trên sân khấu.'],
                price:9400000,
            },
            {
                id:80,
                title:'Takamine GC1',
                img:'./img/product/dan80.jpg',
                category:'Takamine-classic',
                categoryMain:'Guitar Classic',
                details:['Đàn Guitar Takamine GC1NAT là một cây đàn guitar mang phong cách cổ điển với việc sử dụng chất liệu nilon trong sản xuất dây. Chắc chắn cây đàn guitar này sẽ mang lại cho bạn những trải nghiệm tuyệt vời. Đây là sự lựa chọn tuyệt vời cho những người chơi đang tìm kiếm một chiếc guitar cổ điển vừa có chất lượng tốt nhưng giá cả phải chăng.',
    
                'Thiết kế mang phong cách cổ điển, trang nha',
                'Takamine GC1NAT được thiết kế theo phong cách cổ điển, sử dụng chất liệu nilon trong sản xuất dây. Vẻ ngoài mộc mạc nhưng ấn tượng này cũng mê hoặc biết bao tín đồ của đàn guitar trên toàn thế giới.'],
                price:4400000,
            },
            {
                id:81,
                title:'ORTEGA R121-3/4 guitar',
                img:'./img/product/dan81.jpg',
                category:'Takamine-classic',
                categoryMain:'Guitar Classic',
                details:['à ví dụ điển hình cho nghệ thuật luthier, cây đàn guitar cổ điển mang tên Master Luthier Mass Hirade được chế tác bằng tay trong cơ sở Takamine ở Nhật Bản. Mang đến cho người dùng âm thanh hoàn hảo, trong một thiết kế phong cách'],
                price:63950000,
            },
            {
                id:82,
                title:'Fender CN-140SCE',
                img:'./img/product/dan82.jpg',
                category:'Fender-classic',
                categoryMain:'Guitar Classic',
                details:['Cơ thể concert mỏng với cutaway',
    
                 'Mặt top gỗ Cedar rắn với giằng quạt cổ điển',
                
                 'Mặt lưng và hông gỗ Rosewood',
                
                 'Cổ dễ chơi với các cạnh ngón tay cuộn',
                
                 'Hệ thống điện tử Fishman® Classic ',
                
                 'Giai điệu riêng biệt của dây nylon'],
                price:'Liên hệ',
            },
            {
                id:83,
                title:'Fender CN-60S Classical Natural',
                img:'./img/product/dan83.jpg',
                category:'Fender-classic',
                categoryMain:'Guitar Classic',
                details:['Fender CN-60S Classical Natural giúp người trải nghiệm sự thuận tiện của dây Nylon và âm thanh của dây thép'],
                price:5140000,
            },
            {
                id:84,
                title:'Fender CN-60S, Black',
                img:'./img/product/dan84.jpg',
                category:'Fender-classic',
                categoryMain:'Guitar Classic',
                details:['Fender CN-60S Classical Black giúp người trải nghiệm sự thuận tiện của dây Nylon và âm thanh của dây thép'],
                price:6240000,
            },
            {
                id:85,
                title:'Cordoba C1 Full Size',
                img:'./img/product/dan85.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Đàn guitar Cordoba C1 Full Size là sản phẩm có âm thanh tốt, Full Size Nylon Guitar được thiết kế cho những người trẻ trung với cây đàn đầu tiên mang lại cảm giác dễ chịu và thoải mai cho việc học và chơi. Cây đàn có 2 Size là Full Size và 3/4.  C1 được xây dựng mặt Spruce Top với Mahogany Back And Sides, khảm hoa hồng ở lổ thoát âm cùng với lop81 sơn Polyurethane bóng. Như tất cả các sản phẩm của Cordoba, C1 sử dụng dây đản Savarez cùng với thanh Truss-Rod để đảm bảo cần đàn luôn thẳng.'],
                price:3770000,
            },
            {
                id:86,
                title:'Cordoba C5-CE',
                img:'./img/product/dan86.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Cordoba C5-CE được sản xuất dựa trên phiên bản C5 với hệ thống Fishman Isys+ tạo nên âm thanh phong phú và tự nhiên như một cây guitar cổ điển thực thụ. '],
                price:11250000,
            },
            {
                id:87,
                title:'Cordoba 55FCE Thinbody - Honey Amber',
                img:'./img/product/dan87.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Thân đàn mỏng, chống Feedback của 55FCE được làm thủ công khiến cây đàn guitar sản xuất tại Tây Ban Nha này trở thành một công cụ thiết yếu trong kho vũ khí của các nhạc sĩ biểu diễn. Cây đàn được chọn của Gipsy Kings, mặt trên bằng gỗ vân sam châu Âu chắc chắn của nó được kết hợp với mặt sau và mặt bằng gỗ phong rực lửa tuyệt đẹp và lớp hoàn thiện bằng polyurethane nhuộm màu hổ phách mật ong hoặc màu hổ phách tự nhiên.'],
                price:42990000,
            },
            {
                id:88,
                title:'Cordoba Protégé C1 Matiz - Pale Sky',
                img:'./img/product/dan88.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Mang âm nhạc của bạn trở nên sống động với đầy màu sắc với Protégé C1 Matiz! Mang nét thẩm mỹ mới mẻ của cây đàn guitar dây nylon, dòng Matiz kết hợp các điểm nhấn bằng gỗ thích và gỗ có tông màu truyền thống với 4 màu sắc bắt mắt: Aqua, Coral, Pale Sky và Classic Blue. Mặt sau và mặt sau bằng gỗ vân sam và mặt sau bằng gỗ gụ mang lại sự tỏa sáng và ấm áp cho cây đàn guitar dây nylon, trong khi tấm ốp đầu bằng gỗ thích, ngựa đàn và cần đàn toàn diện mang đến cho C1 Matiz một diện mạo hoàn toàn mới với phản ứng âm sắc sống động'],
                price:6480000,
            },
            {
                id:89,
                title:'Cordoba Protégé C1 Matiz - Classic Blue',
                img:'./img/product/dan89.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Mang âm nhạc của bạn trở nên sống động với đầy màu sắc với Protégé C1 Matiz! Mang nét thẩm mỹ mới mẻ của cây đàn guitar dây nylon, dòng Matiz kết hợp các điểm nhấn bằng gỗ thích và gỗ có tông màu truyền thống với 4 màu sắc bắt mắt: Aqua, Coral, Pale Sky và Classic Blue. Mặt sau và mặt sau bằng gỗ vân sam và mặt sau bằng gỗ gụ mang lại sự tỏa sáng và ấm áp cho cây đàn guitar dây nylon'],
                price:6480000,
            },
            {
                id:90,
                title:'Cordoba Protégé C1 Matiz - Coral',
                img:'./img/product/dan90.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Mang âm nhạc của bạn trở nên sống động với đầy màu sắc với Protégé C1 Matiz! Mang nét thẩm mỹ mới mẻ của cây đàn guitar dây nylon, dòng Matiz kết hợp các điểm nhấn bằng gỗ thích và gỗ có tông màu truyền thống với 4 màu sắc bắt mắt: Aqua, Coral, Pale Sky và Classic Blue. Mặt sau và mặt sau bằng gỗ vân sam và mặt sau bằng gỗ gụ mang lại sự tỏa sáng và ấm áp cho cây đàn guitar dây nylon'],
                price:6480000,
            },
            {
                id:91,
                title:'Cordoba Protégé C1 Matiz - AQUA',
                img:'./img/product/dan91.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Mang âm nhạc của bạn trở nên sống động với đầy màu sắc với Protégé C1 Matiz! Mang nét thẩm mỹ mới mẻ của cây đàn guitar dây nylon, dòng Matiz kết hợp các điểm nhấn bằng gỗ thích và gỗ có tông màu truyền thống với 4 màu sắc bắt mắt: Aqua, Coral, Pale Sky và Classic Blue. Mặt sau và mặt sau bằng gỗ vân sam và mặt sau bằng gỗ gụ mang lại sự tỏa sáng và ấm áp cho cây đàn guitar dây nylon'],
                price:6480000,
            },
           
            {
                id:93,
                title:'Cordoba 45 Limited',
                img:'./img/product/dan93.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Âm thanh dây nylon phiên bản giới hạn được chế tác từ các loại gỗ exotic',
    
                 'Mặt sau và mặt sau bằng gỗ mun màu đen và trắng rất ấn tượng',
                
                 'Gỗ vân sam Châu Âu mạnh mẽ và âm thanh rõ ràng',
                
                 'Nut và Saddle làm bằng xương thật'],
                price:37890000,
            },
            {
                id:94,
                title:'Cordoba C4-CE Guclcor-02697',
                img:'./img/product/dan94.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Đầu gỗ gụ châu Phi chắc chắn của guitar Cordoba C4-CE Guclcor-02697 cung cấp một giai điệu rõ ràng, rõ ràng, kết hợp với mặt sau và mặt bằng gỗ gụ châu Phi cho âm lượng cân bằng và duy trì. Việc xây dựng dựa trên cây đàn guitar cổ điển Tây Ban Nha truyền thống của chúng tôi, với sự bao gồm của một đoạn cutaway mềm mại và cổ rộng hơn 50mm được thiết kế để dễ chơi và dễ dàng tiếp cận với thanh ghi trên. Các yếu tố thiết kế cao cấp như liên kết Maple, hoa hồng bào ngư và lớp hoàn thiện Edolturst sẽ giúp bạn nổi bật giữa đám đông. '],
                price:11190000,
            },
            {
                id:95,
                title:'Cordoba C7 CD',
                img:'./img/product/dan95.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Một bước tiến so với C5 của chúng tôi, C7 cung cấp mặt sau và các mặt bằng gỗ hồng sắc với sự lựa chọn của mặt trên bằng gỗ tuyết tùng chắc chắn để đạt được âm thanh dây nylon cổ điển ấm áp hoặc mặt bằng vân sam châu Âu chắc chắn cho âm thanh sáng hơn. Thanh giằng quạt truyền thống của C7 cho phép cộng hưởng tối đa và duy trì và các tính năng cao cấp như hình hoa thị bằng gỗ dát bằng tay, thanh giàn có thể điều chỉnh hai chiều và lớp hoàn thiện PU bóng đẹp.'],
                price:11270000,
            },
            {
                id:96,
                title:'Cordoba C7-CE',
                img:'./img/product/dan96.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Một bước tiến so với C5 của chúng tôi, C7 cung cấp mặt sau và các mặt bằng gỗ hồng sắc với sự lựa chọn của mặt trên bằng gỗ tuyết tùng chắc chắn để đạt được âm thanh dây nylon cổ điển ấm áp hoặc mặt bằng vân sam châu Âu chắc chắn cho âm thanh sáng hơn. Thanh giằng quạt truyền thống của C7 cho phép cộng hưởng tối đa và duy trì và các tính năng cao cấp như hình hoa thị bằng gỗ dát bằng tay, thanh giàn có thể điều chỉnh hai chiều và lớp hoàn thiện PU bóng đẹp.'],
                price:15360000,
            },
            {
                id:97,
                title:'Cordoba 12 Natural CD',
                img:'./img/product/dan97.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Như Tên cho thấy, 12 Natural có 12 phím đàn trên thân, cho phép Bridge nằm sâu hơn trên thùng đàn, nơi cộng hưởng được tối ưu hóa để tạo ra âm thanh lớn với độ bền lâu. Lớp hoàn thiện bằng polyurethane có độ bóng cao làm cho mô hình Fusion này vừa đẹp mắt vừa thiết thực cộng với preamp Fishman Presys tích hợp sẵn.'],
                price:14310000,
            },
            {
                id:98,
                title:'Cordoba GK Studio',
                img:'./img/product/dan98.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Được xây dựng với mặt trên bằng vân sam châu Âu chắc chắn, mặt sau và hai bên bằng gỗ bách, đường cắt mềm mại và tiền khuếch đại Fishman Presys Blend, GK Studio là công cụ biểu diễn tuyệt vời và là sản phẩm bán chạy nhất Córdoba'],
                price:17870000,
            },
            {
                id:99,
                title:'CORDOBA ĐÀN GUITAR NYLON PROTEGE C1M 1/4',
                img:'./img/product/dan99.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Córdoba C1M là cây đàn guitar dây nylon hoàn hảo cho học sinh ở mọi trình độ và hoàn toàn có thể sử dụng trong lớp học hoặc ở nhà. Thoải mái và dễ chơi, đây là cây đàn đầu tiên tuyệt vời với giá cả phải chăng. Mỗi chiếc C1M đều được chế tạo với mặt trên bằng vân sam, mặt sau và hai bên bằng gỗ gụ, cần thoải mái, thanh mảnh, hình hoa thị khảm truyền thống và lớp phủ bằng polyurethane mờ. Giống như tất cả các nhạc cụ Córdoba, các mẫu C1M có dây Savarez cao cấp và thanh giàn có thể điều chỉnh để tạo độ ổn định cho cần suốt đời'],
                price:4460000,
            },
            {
                id:100,
                title:'CORDOBA C1M 02685',
                img:'./img/product/dan100.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Mỗi chiếc C1M đều được chế tạo với mặt trên bằng vân sam, mặt sau và hai bên bằng gỗ gụ, cần thoải mái, thanh mảnh, hình hoa thị khảm truyền thống và lớp phủ bằng polyurethane mờ. Giống như tất cả các nhạc cụ Córdoba, các mẫu C1M có dây Savarez cao cấp và thanh giàn có thể điều chỉnh để tạo độ ổn định cho cần suốt đời'],
                price:4460000,
            },
            {
                id:101,
                title:'CORDOBA ĐÀN GUITAR NYLON PROTEGE 1M-CE',
                img:'./img/product/dan101.jpg',
                category:'Cordoba',
                categoryMain:'Guitar Classic',
                details:['Protégé by Córdoba C1M-CE là cây đàn guitar dây nylon được lựa chọn hàng đầu cho sinh viên ở mọi trình độ và hoàn toàn phù hợp cho cả lớp học và gia đình. Thoải mái và dễ chơi, đây là cây đàn đầu tiên tuyệt vời với giá cả phải chăng. C1M-CE có Cutaway để dễ dàng tiếp cận các phím đàn cao hơn và hệ thống khuếch đại Cordoba GP-2.'],
                price:6570000,
            },
            {
                id:102,
                title:'Squier Fsr Sonic Strat Hss Laurel Surf Green ',
                img:'./img/product/dan102.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Body gỗ mỏng và nhẹ',
                'Cấu hình pickup HSS',
                'Ngựa đàn 6-saddle tremolo giữ cho tremolo có sự ổn định cao',
                'Bộ khoá Sealed Die-Cast giữ được độ chính xác về âm thanh',
                'Bộ hardware Chrome'],
                price:6110000,
            },
            {
                id:103,
                title:'Fender Player Plus Telecaster MN CMJ',
                img:'./img/product/dan103.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Kết hợp giữa thiết kế Fender® cổ điển với các tính năng lấy người chơi làm trung tâm cùng lớp phủ mới thú vị, Player Plus Telecaster® mang đến khả năng chơi tuyệt vời và phong cách không thể nhầm lẫn. Được hỗ trợ bởi một bộ Pickup Player Plus Noiseless ™, Player Plus Tele® mang đến âm thanh Tele® ngọt ngào, ấm áp - không có tiếng xì, ồn'],
                price:25900000,
            },
            {
                id:104,
                title:'Fender AM Ultra Strat Maple HSS UltraBurst ',
                img:'./img/product/dan104.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Fender American Ultra là dòng tốt nhất trong các dòng thuộc series của Fender. Có thể nói, Series American Ultra chỉ dưới Fender Custom Shop. Được xuất hiện vào lần đầu tiên vào năm 2019, Fender American Ultra là thế hệ tiếp theo của dòng American Elite. Vẫn theo những truyền thông của những series trược làm được, series Ultra vẫn giữ được cho mình chất tiếng “Vintage” của một cây đàn bass Fender kết hợp sự đổi mới, công nghệ hiện đại mà hãng “gắn” lên cây đàn này.'],
                price:62100000,
            },
            {
                id:105,
                title:'Fender AM Ultra Strat Maple HSS Texas Tea',
                img:'./img/product/dan105.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Fender American Ultra là dòng tốt nhất trong các dòng thuộc series của Fender. Có thể nói, Series American Ultra chỉ dưới Fender Custom Shop. Được xuất hiện vào lần đầu tiên vào năm 2019, Fender American Ultra là thế hệ tiếp theo của dòng American Elite. Vẫn theo những truyền thông của những series trược làm được, series Ultra vẫn giữ được cho mình chất tiếng “Vintage” của một cây đàn bass Fender kết hợp sự đổi mới, công nghệ hiện đại mà hãng “gắn” lên cây đàn này'],
                price:57900000,
            },
            {
                id:106,
                title:'Fender Mij Fsr-Collection Hydrid Ii Strat Rosewood, Deep Ocean Metallic',
                img:'./img/product/dan106.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Fender American Ultra là dòng tốt nhất trong các dòng thuộc series của Fender. Có thể nói, Series American Ultra chỉ dưới Fender Custom Shop. Được xuất hiện vào lần đầu tiên vào năm 2019, Fender American Ultra là thế hệ tiếp theo của dòng American Elite. Vẫn theo những truyền thông của những series trược làm được, series Ultra vẫn giữ được cho mình chất tiếng “Vintage” của một cây đàn bass Fender kết hợp sự đổi mới, công nghệ hiện đại mà hãng “gắn” lên cây đàn này'],
                price:30470000,
            },
            {
                id:107,
                title:'Fender Mij Fsr-Collection Hydrid Ii Strat Rosewood, Daphne Blue ',
                img:'./img/product/dan107.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Fender American Ultra là dòng tốt nhất trong các dòng thuộc series của Fender. Có thể nói, Series American Ultra chỉ dưới Fender Custom Shop. Được xuất hiện vào lần đầu tiên vào năm 2019, Fender American Ultra là thế hệ tiếp theo của dòng American Elite. Vẫn theo những truyền thông của những series trược làm được, series Ultra vẫn giữ được cho mình chất tiếng “Vintage” của một cây đàn bass Fender kết hợp sự đổi mới, công nghệ hiện đại mà hãng “gắn” lên cây đàn này'],
                price:30470000,
            },
            {
                id:108,
                title:'SQUIER® STRATOCASTER® PACK',
                img:'./img/product/dan108.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Một sự lựa chọn hoàn hảo cho người mới bắt đầu, Squier Strat Pack có mọi thứ bạn cần để bắt đầu chơi ngay từ đầu. Stratocaster lý tưởng cho người chơi mới bắt đầu và mang lại cảm giác chơi thoải mái. Nó bao gồm một thân đàn nhẹ, một cây cầu tremolo phong cách cổ điển cho hiệu ứng cao độ cổ điển và ba Pickup singlecoi cho giai điệu Strat cổ điển. Chúng tôi cũng bao gồm đăng ký 3 tháng miễn phí cho Fender Play® — cách dễ nhất để học guitar.'],
                price:8000000,
            },
            {
                id:109,
                title:'Fender Player Plus Stratocaster®',
                img:'./img/product/dan109.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Kết hợp giữa thiết kế Fender® cổ điển với các tính năng hỗ trợ người chơi và lớp phủ mới thú vị, Player Plus Stratocaster® mang đến khả năng chơi tuyệt vời và phong cách không thể nhầm lẫn. Trọng tâm của Series này là bộ ba Pickup Player Plus Noiseless ™ - sáng,nhạy, chúng cung cấp giai điệu Strat cổ điển mà không có tiếng ồn. Một nút Push/Pull trên bộ điều khiển giai điệu bổ sung để chuyển đổi vị trí 1 và 2 cho hai âm thanh không thường thấy trên Strat®'],
                price:27000000,
            },
            {
                id:110,
                title:'FENDER EOB SUSTAINER STRATOCASTER®',
                img:'./img/product/dan110.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Thoạt nhìn, Limited Edition 1962 Stratocaster có vẻ là một nhạc cụ cổ điển thực sự được chơi và yêu thích trên các sân khấu trong nhiều năm. Tuy nhiên, khi kiểm tra kỹ hơn, người chơi sẽ thấy sự sáng tạo này chứa đầy những viên ngọc ẩn để có trải nghiệm chơi tuyệt vời. Một thân đàn chọn lọc gồm hai mảnh mang lớp sơn mài của Journeyman Relic, trong khi phần cần bằng gỗ phong xẻ rãnh nhuộm màu có kiểu dáng “hình bầu dục C” kiểu 60’ thoải mái, với Fingerboard bằng gỗ phong nhiều lớp phẳng nguyên mẫu.'],
                price:36230000,
            },
            {
                id:111,
                title:'Fender B1 LTD 1962 STRAT MPL BT JRN - SFASNB',
                img:'./img/product/dan111.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Thoạt nhìn, Limited Edition 1962 Stratocaster có vẻ là một nhạc cụ cổ điển thực sự được chơi và yêu thích trên các sân khấu trong nhiều năm. Tuy nhiên, khi kiểm tra kỹ hơn, người chơi sẽ thấy sự sáng tạo này chứa đầy những viên ngọc ẩn để có trải nghiệm chơi tuyệt vời. Một thân đàn chọn lọc gồm hai mảnh mang lớp sơn mài của Journeyman Relic, trong khi phần cần bằng gỗ phong xẻ rãnh nhuộm màu có kiểu dáng “hình bầu dục C” kiểu 60’ thoải mái, với Fingerboard bằng gỗ phong nhiều lớp phẳng nguyên mẫu.'],
                price:122390000,
            },
            {
                id:112,
                title:'Fender Squier Affinity Series™ Telecaster®',
                img:'./img/product/dan112.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Là một cửa ngõ tuyệt vời vào gia đình Fender® lâu đời, Squier® Affinity Series ™ Telecaster® mang đến thiết kế huyền thoại và giai điệu tinh túy cho người dùng guitar đầy khát vọng ngày nay. Tele® này có một số cải tiến thân thiện với người chơi như cần hình chữ “C” mỏng và thoải mái, Bridge 6-Point để điều chỉnh ngữ điệu tốt và khoá lên dây đúc kín để điều chỉnh mượt mà, chính xác.'],
                price:6200000,
            },
            {
                id:113,
                title:'Ltd Ed Carlos Lopez Masterbuilt Eric Johnson Virginia Stratocaster',
                img:'./img/product/dan113.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Mỗi công cụ Custom Shop Limited Edition chỉ có sẵn trong thời gian ngắn, điều này làm cho nó có thể sưu tầm được và làm tăng thêm giá trị đầu tư của nó. Được chế tạo với nhiều tính năng chỉ dành riêng cho một số nghệ sĩ và nhạc cụ chế tạo bậc thầy, chúng đúng như tên gọi: các mẫu phiên bản giới hạn rất được mong đợi sẽ ra mắt rất nhanh.'],
                price:'Liên hệ',
            },
            {
                id:114,
                title:'64 Stratocaster - Journeyman Relic w/ Closet Classic Hardware',
                img:'./img/product/dan114.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Mỗi công cụ Custom Shop Limited Edition chỉ có sẵn trong thời gian ngắn, điều này làm cho nó có thể sưu tầm được và làm tăng thêm giá trị đầu tư của nó. Được chế tạo với nhiều tính năng chỉ dành riêng cho một số nghệ sĩ và nhạc cụ chế tạo bậc thầy, chúng đúng như tên gọi: các mẫu phiên bản giới hạn rất được mong đợi sẽ ra mắt rất nhanh.'],
                price:120960000,
            },
            {
                id:115,
                title:'Fender Player Stratocaster® HSS',
                img:'./img/product/dan115.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['Fender Player HSS Strat là cách tốt nhất cho những người chơi guitar có ngân sách tiết kiệm để sở hữu một chiếc Fender Stratocaster thực sự với một chiếc humbucker nổi bật và hai chiếc pickups đơn. Player Series Stratocasters được sản xuất tại Mexico (MIM). Cây đàn nghe rất tuyệt, và đẹp như những người anh em Mỹ của họ, và có những gì cần thiết để có thể bùng cháy cả khi tập luyện lẫn trên sân khấu tại câu lạc bộ'],
                price:24140000,
            },
            {
                id:116,
                title:'Fender American Standard V Jazz Bass Guitar 0193750700',
                img:'./img/product/dan116.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['American Standard Jazz Bass V năm dây là nhạc cụ linh hoạt kiểu dáng đẹp mà nó luôn có - một nhạc cụ xe đua dành cho người chơi bass muốn dải năm dây lớn hơn để hát, gầm gừ, rãnh và gầm gừ.'],
                price:29900000,
            },
            {
                id:117,
                title:'American Professional II Jazz Bass® V',
                img:'./img/product/dan117.jpg',
                category:'Fender-điện',
                categoryMain:'Guitar điện',
                details:['American Professional II Jazz Bass® dựa trên hơn sáu mươi năm đổi mới, truyền cảm hứng và tiến hóa để đáp ứng nhu cầu của các nhạc sĩ chuyên nghiệp ngày nay. Cổ “Slim C” phổ biến của chúng tôi hiện nay có các cạnh phím đàn tròn nhẵn, lớp hoàn thiện bằng satin “Siêu tự nhiên” và phần gót cổ được điêu khắc mới cho cảm giác cực kỳ thoải mái và dễ dàng truy cập vào thanh ghi phía trên'],
                price:52490000,
            },
           
            {
                id:119,
                title:'JS SERIES KELLY™ JS32T, AMARANTH FINGERBOARD',
                img:'./img/product/dan119.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['Nhanh chóng, đáng kinh ngạc và giá cả phải chăng, guitar Jackson® JS Series có một bước tiến vượt bậc, giúp bạn có được giai điệu Jackson cổ điển, ngoại hình và khả năng chơi dễ dàng hơn bao giờ hết.'],
                price:9850000,
            },
            {
                id:120,
                title:'JS SERIES KING V™ JS32T, AMARANTH FINGERBOARD, GLOSS BLACK',
                img:'./img/product/dan120.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['JS32T King V có thân hình cây dương, cần bằng gỗ thích bắt vít với gia cố bằng than chì và Fingerboard có bán kính hợp chất 12 ”-16” với 24 phím đàn jumbo và khảm'],
                price:7290000,
            },
            {
                id:121,
                title:'JS SERIES MONARKH SC JS22Q, AMARANTH FINGERBOARD, TRANSPARENT PURPLE BURST',
                img:'./img/product/dan121.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['SC JS22Q cung cấp chiều dài quy mô ngắn hơn một chút (24,75 ") so với hầu hết các cây đàn guitar sáu dây của chúng tôi và có thân hình cây dương với mặt trên bằng maple đẹp mắt. Được thiết kế cho chơi linh hoạt, bàn phím đàn dền bán kính ghép 12 "-16" được uốn cong để dễ dàng chơi hợp âm gần, làm phẳng để chơi các dây sau mà không sợ bị khó khăn khi Bend dây'],
                price:9360000,
            },
            {
                id:122,
                title:'JS SERIES KING V™ JS32, AMARANTH FINGERBOARD',
                img:'./img/product/dan122.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['Chiếc King V đáng gờm này có thân hình cây dương, cần đàn bằng gỗ thích gắn chốt với gia cố bằng than chì và khớp nối vành khăn để tạo sự ổn định vững chắc như đá. Fingerboard bán kính hợp chất 12 "-16" của nó có 24 phím đàn jumbo và khảm vây cá mập lê.'],
                price:12360000,
            },
            {
                id:123,
                title:'Fender Jcks Pro SL3M RAINBOW',
                img:'./img/product/dan123.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['Các tính năng cao cấp của Pro SL3M bao gồm thân gỗ trầm cộng hưởng và cần gỗ thích xuyên suốt thân với khớp vành khăn và các thanh gia cố bằng than chì cung cấp độ cứng và ổn định để bảo vệ chống lại sự uốn cong và cong vênh do nhiệt độ và độ ẩm gây ra. Lưu trữ 24 phím đàn jumbo và khảm răng piranha đen, Fingerboard gỗ phong bán kính kết hợp 12 ”-16” với 24 phím đàn jumbo được thiết kế để chơi với tốc độ kỹ thuật cao — cong hơn bởi đai ốc để bấm hợp âm thoải mái, nó phẳng ra khi bạn di chuyển lên cần cho tốc độ chơi ngày càng nhanh và uốn cong rộng mà không lo lắng.'],
                price:32200000,
            },
            {
                id:124,
                title:'Fender JCKS X SLXDX SILVBURST',
                img:'./img/product/dan124.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['SLX DX có body gỗ dương, cần bằng gỗ thích xuyên suốt với phần gia cố bằng than chì và phần đầu có khớp thắt khăn nghiêng về phía sau. Lưu trữ 24 phím đàn jumbo, Finger board bán kính hợp chất liên kết hoàn toàn 12 "-16" của nó uốn cong đáng kể hơn ở đai ốc để dễ dàng lựa chọn và làm phẳng khi nó tiếp cận khớp cổ để uốn cong tác động thấp mà không phải lo lắng.'],
                price:18390000,
            },
            {
                id:125,
                title:'jackson PRO MM JUGG ET7 - GULF BLUE',
                img:'./img/product/dan125.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['Pro Series Signature Misha Mansoor Juggernaut ET7 cung cấp chiều dài quy mô 26,5 ”, thân bằng gỗ trầm và cần đàn bằng gỗ phong caramel với gia cố bằng than chì rắn chắc, phần gót bọc xung quanh và mặt sau được phủ dầu để mang lại sự thoải mái hơn khi chơi. Tận hưởng những đường solo nhanh chóng mặt với fingerboard gỗ phong caramel bán kính phẳng 20 inch có các cạnh cuộn, 24 phím đàn jumbo và các lớp khảm chấm bù. Các chấm bên phát sáng sẽ dẫn đường cho bạn ngay cả trong không gian tối nhất của sân khấu'],
                price:'Liên hệ',
            },
    
            {
                id:126,
                title:'X SERIES DINKY™ ARCH TOP DKAF7 MS, LAUREL FINGERBOARD, MULTI-SCALE, GLOSS BLACK',
                img:'./img/product/dan126.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['DKAF7 có chiều dài đa tỷ lệ 25,5 "-27", thân cây dương với headstock hình vòm, cần bằng gỗ thích có chốt với gia cố bằng than chì và khớp nối vành khăn, fingerboard bán kính ghép 12 "-16" với 24 phím đàn jumbo và lớp khảm chấm bù, Bộ điều chỉnh đúc khuôn Jackson và móc cài 4x3 AT-1.'],
                price:'Liên hệ',
            },
            {
                id:127,
                title:'JS SERIES CONCERT™ BASS JS3, AMARANTH FINGERBOARD, SATIN BLACK',
                img:'./img/product/dan127.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['Concert Bass JS3 là một cây đàn bass bốn dây, kích thước 34 inch có body gỗ dương nhẹ và vang, cần đàn bằng gỗ thích được gia cố bằng than chì và bàn phím đàn dền có bán kính hợp chất 12 inch -16 ”với 24 phím đàn jumbo và vây cá mập lê lớp phủ.'],
                price:'Liên hệ',
            },
            {
                id:128,
                title:'JS SERIES MONARKH SC JS22, AMARANTH FINGERBOARD, SNOW WHITE',
                img:'./img/product/dan128.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['SC JS22 cung cấp chiều dài quy mô ngắn hơn một chút (24,75 ") so với hầu hết các cây đàn guitar sáu dây. Được thiết kế để chơi linh hoạt, đàn 12" -Fingerbaord amaranth bán kính kép 16 "được uốn cong để dễ dàng chơi hợp âm.'],
                price:7430000,
            },
            {
                id:129,
                title:'JS SERIES WARRIOR™ JS32T, AMARANTH FINGERBOARD, NATURAL OIL',
                img:'./img/product/dan129.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['Warrior ™ JS32T đáng gờm có thân nato và cần bằng gỗ thích bắt vít với gia cố bằng than chì để tạo sự ổn định vững chắc như đá. Lưu trữ 24 phím đàn jumbo và khảm vây cá mập, bán kính hợp chất 12 ”-16” tạo ra bề mặt chơi lý tưởng cho các bài hát và cho các bản solo nhanh như chớp.'],
                price:8120000,
            },
            {
                id:130,
                title:'JS SERIES DINKY™ ARCH TOP JS24 DKAM, CARAMELIZED MAPLE FINGERBOARD, RED STAIN',
                img:'./img/product/dan130.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['JS Series JS Dinky ™ Arch Top JS24 DKAM có thân bằng gỗ gụ với Headstock và cần đàn tốc độ bằng gỗ phong caramel bắt vít với gia cố bằng than chì để tạo độ ổn định vững chắc như đá, giảm sự mệt mỏi khi chơi. Được thiết kế cho tốc độ nhanh và sự thoải mái, bàn phím gỗ phong caramel có bán kính hợp chất 12 ”-16” của nó có 24 phím đàn jumbo và khảm vây cá mập đen.'],
                price:10050000,
            },
            {
                id:131,
                title:'jackson 2910121557 JS SERIES DINKY™ ARCH TOP JS22 DKA, AMARANTH FINGERBOARD',
                img:'./img/product/dan131.jpg',
                category:'Jackson',
                categoryMain:'Guitar điện',
                details:['Nhanh chóng, tuyệt vời và giá cả phải chăng, những cây đàn Jackson JS Series có một bước tiến vượt bậc, giúp bạn có được giai điệu Jackson cổ điển, ngoại hình và khả năng chơi dễ dàng hơn bao giờ hết'],
                price:6480000,
            },
            {
                id:132,
                title:'Squier Fsr Sonic Strat Maple Surf Green',
                img:'./img/product/dan132.jpg',
                category:'Squier',
                categoryMain:'Guitar điện',
                details:['Body gỗ mỏng và nhẹ',
                'Cấu hình pickup SSS',
                'Ngựa đàn 6-saddle tremolo giữ cho tremolo có sự ổn định cao',
                'Bộ khoá Sealed Die-Cast giữ được độ chính xác về âm thanh',
                'Bộ hardware Chrome'],
                price:6010000,
            },
            {
                id:133,
                title:'Squier Fsr Sonic Strat Maple Tahitian Coral ',
                img:'./img/product/dan133.jpg',
                category:'Squier',
                categoryMain:'Guitar điện',
                details:['Body gỗ mỏng và nhẹ',
                'Cấu hình pickup SSS',
                'Ngựa đàn 6-saddle tremolo giữ cho tremolo có sự ổn định cao',
                'Bộ khoá Sealed Die-Cast giữ được độ chính xác về âm thanh',
                'Bộ hardware Chrome'],
                price:6010000,
            },
            {
                id:134,
                title:'Squier Fsr Sonic Strat Maple Arctic White ',
                img:'./img/product/dan134.jpg',
                category:'Squier',
                categoryMain:'Guitar điện',
                details:['Body gỗ mỏng và nhẹ',
                'Cấu hình pickup SSS',
                'Ngựa đàn 6-saddle tremolo giữ cho tremolo có sự ổn định cao',
                'Bộ khoá Sealed Die-Cast giữ được độ chính xác về âm thanh',
                'Bộ hardware Chrome'],
                price:6010000,
            },
            {
                id:135,
                title:'Squier Fsr Sonic Strat Laurel Arctic White',
                img:'./img/product/dan135.jpg',
                category:'Squier',
                categoryMain:'Guitar điện',
                details:['Body gỗ mỏng và nhẹ',
                'Cấu hình pickup SSS',
                'Ngựa đàn 6-saddle tremolo giữ cho tremolo có sự ổn định cao',
                'Bộ khoá Sealed Die-Cast giữ được độ chính xác về âm thanh',
                'Bộ hardware Chrome'],
                price:6110000,
            },
            {
                id:136,
                title:'Squier Fsr Sonic Strat Hss Maple California Blue',
                img:'./img/product/dan136.jpg',
                category:'Squier',
                categoryMain:'Guitar điện',
                details:['Body gỗ mỏng và nhẹ',
                'Cấu hình pickup HSS',
                'Ngựa đàn 6-saddle tremolo giữ cho tremolo có sự ổn định cao',
                'Bộ khoá Sealed Die-Cast giữ được độ chính xác về âm thanh',
                'Bộ hardware Chrome'],
                price:6110000,
            },
            {
                id:138,
                title:'Đàn Guitar Charvel Pro-Mod San Dimas HH FR, Black Burst',
                img:'./img/product/dan138.jpg',
                category:'charvel',
                categoryMain:'Guitar điện',
                details:['Body gỗ mỏng và nhẹ',
                'Cấu hình pickup HSS',
                'Ngựa đàn 6-saddle tremolo giữ cho tremolo có sự ổn định cao',
                'Bộ khoá Sealed Die-Cast giữ được độ chính xác về âm thanh',
                'Bộ hardware Chrome'],
                price:22460000,
            },
            
            
           
        ]
        localStorage.setItem('products',JSON.stringify(products));
    }
    
    
}
window.onload = initProducts();